name: 'Deploy to Test PyPI'
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'install dependencies'
        run: |
          python3 -m pip install --upgrade wheel
          python3 -m pip install --upgrade setuptools
          python3 -m pip install --upgrade twine
      - name: 'build'
        run: python3 setup.py sdist bdist_wheel

      - name: 'publish'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
